### PR TITLE
Config allow path change to build storybook

### PR DESCRIPTION
**Pull request by vunam2000**

### CODE REVIEW

**Comment by vunam2000** [comment]
The deployed Storybook is available on Chromatic: https://64337ab552933871acec5f96-teyoqdifwc.chromatic.com/

**Comment by vunam2000** [comment]
The deployed Storybook is available on Chromatic: https://64337ab552933871acec5f96-bpznwjchyr.chromatic.com/

**Comment by vunam2000** [comment]
The deployed Storybook is available on Chromatic: https://64337ab552933871acec5f96-eiysunwcyu.chromatic.com/

**Comment by vunam2000** [comment]
The deployed Storybook is available on Chromatic: https://64337ab552933871acec5f96-krvnffyalq.chromatic.com/

**Review by fallingforest — APPROVED** [review]
Updated github action to built on merge main only

**Pull request merged**
